SELECT 
    `COLUMN_NAME`,
    `ORDINAL_POSITION`,
    `COLUMN_DEFAULT`,
    `IS_NULLABLE`,
    `DATA_TYPE`,
    `CHARACTER_MAXIMUM_LENGTH`,
    `NUMERIC_PRECISION`,
    `COLUMN_TYPE`,
    `COLUMN_COMMENT`,
    `GENERATION_EXPRESSION`
FROM `INFORMATION_SCHEMA`.`COLUMNS`
WHERE UPPER(`TABLE_SCHEMA`) LIKE UPPER('{0}') 
    AND UPPER(`TABLE_NAME`) LIKE UPPER('{1}')
