SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  UPPER(REFERENCED_TABLE_SCHEMA) LIKE UPPER('{0}') AND
  UPPER(REFERENCED_TABLE_NAME) LIKE UPPER('{1}');
